program show range of input number
lukaszkutylowski/learnProgramming pull request #15
Opened 2018-12-10 15:56 UTC by lukaszkutylowski

2018-12-10 21:36 UTC, MatDls requested changes
That's great. But let's not stick tho that.
Try to pass argument by args instead of using Scanner.
Can you do that please?:)

2018-12-12 20:32 UTC, lukaszkutylowski commented
@MatDls 
args done :)

2018-12-13 18:20 UTC, MatDls approved these changes
It's good, but let's practice a little more.
Try to implement my comments before merging:)

2018-12-13 18:20 UTC, MatDls commented on exercisePPJ_07_I/ExercisePPJ_07_I.java
> +		//code change - input from args
Do not leave commented code. (If you ever want to go back to code you once commited - you can do it in git)

2018-12-13 18:20 UTC, MatDls commented on exercisePPJ_07_I/ExercisePPJ_07_I.java
> +		int wrt = Integer.parseInt(wrtS);
Inline those two lines

2018-12-13 18:20 UTC, MatDls commented on exercisePPJ_07_I/ExercisePPJ_07_I.java
> +		}
you have two print statements.
Try do do that with one, and print variable which depends on if condition.
Try to use if only, (without else) ;)

2018-12-13 20:35 UTC, lukaszkutylowski commented
@MatDls 
all topics done, please check :)

2019-02-25 16:14 UTC, merged