Exercises ppj
lukaszkutylowski/learnProgramming pull request #3
Opened 2018-11-28 09:08 UTC by lukaszkutylowski

2018-11-29 14:57 UTC, MatDls requested changes
too many files for one PR. please, split it.

2018-11-29 18:19 UTC, MatDls commented
you work pretty faat, that's super cool:)

2018-11-29 21:04 UTC, lukaszkutylowski commented
Ok, I read about split PRs but I think the most advantageous is reupload files in new commit and create pull request. In this situation create new branches and delete old branch to split one RP is pointless. I'm going to work

2018-11-29 21:52 UTC, lukaszkutylowski commented
I should add one file (or main file + method file) in another branch? I cannot add for example 30 files in one branch? (branch = pull request, i see). Because only way to split pull request is create new branches

2018-12-10 21:33 UTC, MatDls requested changes
Gnerally, it looks nice. 
But, for practice please:
Split this pull int two.
One with Exc. 04_* other wiht Exc. 05_*
I think you will fugure out how to do that:)

2018-12-10 21:33 UTC, MatDls commented on ExercisesPPJ/ExercisePPJ_04_4.java
> +	else if((x < 100) && (x >= 10)) {
those parenthesis are not necessary, but they are ok

2018-12-10 21:33 UTC, MatDls commented on ExercisesPPJ/ExercisePPJ_04_2.java
> +}
indentation, please:)

2018-12-10 21:33 UTC, MatDls commented on ExercisesPPJ/ExercisePPJ_04_2.java
> +}
indentation - in may places:)
Please, be careful about that:)

2018-12-11 20:31 UTC, closed without merging