Exercise ppj 05 III
lukaszkutylowski/learnProgramming pull request #5
Opened 2018-11-30 17:01 UTC by lukaszkutylowski

2018-12-03 23:00 UTC, MatDls requested changes

2018-12-03 23:00 UTC, MatDls commented on Fibonacci.java
> -}
Hey @lukaszkutylowski 
Do you understand what's going on here?
Please, explain if this was intentional.
If not, then please correct.
If yes - than please explain it to me.
Use @ sign to mention me somewhere or just call If that's easier

2018-12-04 19:19 UTC, MatDls commented on Fibonacci.java
> -}
Hey Man!
Why you didn't answer?
:)

Don't be shy, reply:)

2018-12-06 16:30 UTC, lukaszkutylowski commented
@MatDls 
so it's all good? I can merge?

2018-12-13 19:05 UTC, lukaszkutylowski commented
@MatDls 
maybe I wrote not clearly, but position of array is number from 0, but Fibonacci series have not 0 position - 1st element of series, 2nd element etc. but 0st element? rather not. zero position in array is first position of series. in this situation if user want see 1st element program must have 0 position of array.

2018-12-13 19:08 UTC, merged